### ISSUE TITLE
What good is one issue

### ISSUE THREAD

**Issue by ivanlei** [ivanlei/ProjectsExplorer#2]
I mean seriously is it worth a dang?

**Comment by ivanlei** [comment]
```[tasklist]
### Tasks
- [ ] https://github.com/octo-org/octo-repo/issues/45
- [ ] Draft issue title
```

**Comment by ivanlei** [comment]
- [ ] this is one task
- [ ] this is another task
- [ ] tasks i say
- [ ] so many
